# Alacritty configuration, more options at
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

import:
  - ~/Developer/dots/config/alacritty/themes/gruvbox_dark.yaml
  #  - ~/Developer/dots/config/alacritty/themes/gruvbox_light.yaml

window:
  dimensions:
    columns: 180
    lines: 40
  decorations: buttonless
  padding:
    x: 5
    y: 0
  opacity: 1.0

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  offset:
    y: 4
    x: 0
  size: 12.0

alt_send_esc: false

key_bindings:
    - { key: N, mods: Command, action: CreateNewWindow }
