# Alacritty configuration, more options at
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

import:
  - ~/Developer/dots/config/alacritty/themes/tokyonight-storm.yaml
  # - ~/Developer/dots/config/alacritty/themes/tokyonight-day.yaml
  # - ~/Developer/dots/config/alacritty/themes/gruvbox_dark.yaml
  # - ~/Developer/dots/config/alacritty/themes/gruvbox_light.yaml

window:
  dimensions:
    columns: 180
    lines: 40
  decorations: buttonless
  padding:
    x: 5
    y: 0
  opacity: 1.0
  option_as_alt: OnlyLeft

font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular
  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: SauceCodePro Nerd Font Mono
    style: Italic
  bold_italic:
    family: SauceCodePro Nerd Font Mono
    style: Bold Italic
  offset:
    y: 0
    x: 0
  size: 13.0

key_bindings:
  - { key: Return, mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return, mods: Control, chars: "\x1b[13;5u" }
  - { key: Space,  mods: Shift,   chars: "\x1b[32;2u" }
