# Alacritty configuration, more options at
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

import:
  - ~/Developer/alacritty-theme/themes/gruvbox_dark.yaml

window:
  decorations: none # full, none, transparent or buttonless
  opacity: 1

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  offset:
    y: 4
    x: 0
  size: 12.0
  use_thin_strokes: false # for retina displays set to true

alt_send_esc: false
